name: WinUSB installer Build, Test

on:
  push:
    branches:
          - 'features/2-cdci-create-gitlab-workflow' #'*'  # This will run the build and test jobs for pull requests to all branches
     

  # pull_request:
  #   branches:
  #     - '*'  # This will run the build and test jobs for pull requests to all branches

env:
  WDK_8_PKG_URL: "https://go.microsoft.com/fwlink/p/?LinkID=253170"
jobs:
  release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create and enter the build directory
        run: |
          mkdir build
          cd build

      - name: Download WDK 8 and install component
        run: |
          Invoke-WebRequest -Uri ${{ env.WDK_8_PKG_URL }} -OutFile wdfcoinstaller.msi
          msiexec /i wdfcoinstaller.msi /qn /l*v install.log

